### ISSUE TITLE
请问这个项目可以用来检测一张图片是否包含摩尔纹吗？

### ISSUE THREAD

**Issue by BerryRB** [ZhengJun-AI/MoirePhotoRestoration-MCNN#1]
看了您的博客过来的

**Comment by ZhengJun-AI** [comment]
你好啊。
这个项目只能够消除摩尔纹，并不能检测摩尔纹…并且这个模型的效果其实比较一般，如果你有兴趣的话推荐你去了解一下华为研究院2019年的最新成果。
（当然了，我觉得有一种方法就是丢张图片进去处理以后和原图进行对比，看差异大不大…虽然这个方法听起来不太靠谱就是了）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhengJun-AI/MoirePhotoRestoration-MCNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 晚上8:03
收件人:&nbsp;"ZhengJun-AI/MoirePhotoRestoration-MCNN"<MoirePhotoRestoration-MCNN@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ZhengJun-AI/MoirePhotoRestoration-MCNN] 请问这个项目可以用来检测一张图片是否包含摩尔纹吗？ (#1)





 
看了您的博客过来的

**Comment by BerryRB** [comment]
> 你好啊。 这个项目只能够消除摩尔纹，并不能检测摩尔纹…并且这个模型的效果其实比较一般，如果你有兴趣的话推荐你去了解一下华为研究院2019年的最新成果。 （当然了，我觉得有一种方法就是丢张图片进去处理以后和原图进行对比，看差异大不大…虽然这个方法听起来不太靠谱就是了）
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ZhengJun-AI/MoirePhotoRestoration-MCNN" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月28日(星期五) 晚上8:03 收件人:&nbsp;"ZhengJun-AI/MoirePhotoRestoration-MCNN"<MoirePhotoRestoration-MCNN@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[ZhengJun-AI/MoirePhotoRestoration-MCNN] 请问这个项目可以用来检测一张图片是否包含摩尔纹吗？ (#1) 看了您的博客过来的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

博主，你的博客中的大数据集有百度网盘版本吗？谷歌云盘下载了两天了，总是下载到一半就崩溃了，然后被禁止，只能过24小时再试...

**Comment by ZhengJun-AI** [comment]
没有…我当初也是下载了好久，要选一个好一点的梯子，而且要挑一些特别的、人比较少的时间段去下载




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BerryRB"<notifications@github.com&gt;; 
发送时间: 2020年8月31日(星期一) 下午4:00
收件人: "ZhengJun-AI/MoirePhotoRestoration-MCNN"<MoirePhotoRestoration-MCNN@noreply.github.com&gt;; 
抄送: "zxbsmk"<3028208898@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ZhengJun-AI/MoirePhotoRestoration-MCNN] 请问这个项目可以用来检测一张图片是否包含摩尔纹吗？ (#1)





  
你好啊。 这个项目只能够消除摩尔纹，并不能检测摩尔纹…并且这个模型的效果其实比较一般，如果你有兴趣的话推荐你去了解一下华为研究院2019年的最新成果。 （当然了，我觉得有一种方法就是丢张图片进去处理以后和原图进行对比，看差异大不大…虽然这个方法听起来不太靠谱就是了）
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ZhengJun-AI/MoirePhotoRestoration-MCNN" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月28日(星期五) 晚上8:03 收件人:&nbsp;"ZhengJun-AI/MoirePhotoRestoration-MCNN"<MoirePhotoRestoration-MCNN@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[ZhengJun-AI/MoirePhotoRestoration-MCNN] 请问这个项目可以用来检测一张图片是否包含摩尔纹吗？ (#1) 看了您的博客过来的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
博主，你的博客中的大数据集有百度网盘版本吗？谷歌云盘下载了两天了，总是下载到一半就崩溃了，然后被禁止，只能过24小时再试...
